const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
	name: String,
	questions: [{
		name: String,
		answer: Number
	}],
	profileType: String
});

module.exports = mongoose.model('User', UserSchema);

/*
EXAMPLE BODY STRUCTURE FOR POSTMAN
----------------------------------
{
	name: "Liana Ali",
	questions: [{
		name: "Saving Amount",
		answer: 10000
	}, {
		name: "Loan Amount",
		answer: 2000
	}]
}
*/

/*
PROPOSED SCHEMA (FOR SCALABLE SYSTEM)
-------------------------------------
1. User
2. Question
3. Answer
4. Profile

DETAILS
-------
1. USER SCHEMA
{
	_id: xxxx							// Auto-generated by MongoDB
	name: String,						// "Liana Ali"
	questions: [{
		q_id: Schema.Types.ObjectId,	// _id from Question Schema
		a_id: Schema.Types.ObjectId		// _id from Answer Schema
	}],
	p_id: Schema.Types.ObjectId			// _id from Profile Schema
}

2. QUESTION SCHEMA
{
	_id: xxxx							// Auto-generated by MongoDB
	name: String,						// "What is your saving amount?"
	answer: [{ Schema.Types.ObjectId }]	// All answers in Answer Schema with q_id=_id from Question Schema
}

3. ANSWER SCHEMA
{
	_id: xxxx						// Auto-generated by MongoDB
	q_id: Schema.Types.ObjectId,	// _id from Question Schema
	name: String,					// "10000"
	score: Number					// 6
}

4. PROFILE SCHEMA
{
	_id: xxxx			// Auto-generated by MongoDB
	profile: String,	// "A"
	min_score: Number	// 8
}
*/